### ISSUE TITLE
Xolli pull request

### ISSUE THREAD

**Issue by xolli** [hackerembassy/hackerembassy-tg-bot#6]
- Refactoring
- ~Сделать красивым Readme~
- Вынести ответы бота из кода программы

**Comment by xolli** [comment]
@tectonick предложил хранить шаблоны в JSON файле в ресурсах. Соответственно, в папке `data` будет лежать JSON файл, в котором в качестве ключа будет использоваться имя шаблона, а значением будет сам шаблон

**Comment by tectonick** [comment]
Решили все-таки в YAML для читаемости мультистрочных сообщений

**Comment by tectonick** [comment]
Процесс выноса в ресурсы сделан, осталось только обновить TextGenerators
